---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
spec:
  selector:
    matchLabels:
      app: middleware
  replicas: 1
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
        - name: middleware
          image: sampath333/middleware:latest
          ports:
            - containerPort: 5001
          env:
            - name: MYSQL_HOST
              value: "phishing-mysql"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: phishing-mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phishing-mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: "phishing_db"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: middleware
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: middleware
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: middleware-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: middleware
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30