---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-service-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/phishing-mlService
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  selector:
    matchLabels:
      app: model-service
  replicas: 1
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model-service
          image: aaradhyaghota/model-service:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "400m"
              memory: "1Gi"
          # securityContext:
          #   runAsUser: 1000
          #   runAsGroup: 1000
          volumeMounts:
            - name: phishing-mlservice-storage
              mountPath: /var/lib/mlService/data
              subPath: data
            - name: phishing-mlservice-storage
              mountPath: /var/lib/mlService/ml-model
              subPath: ml-model
      volumes:
        - name: phishing-mlservice-storage
          persistentVolumeClaim:
            claimName: ml-service-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: model-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: model-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: model-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
