---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: phishing-mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/phishing-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phishing-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-mysql
spec:
  selector:
    matchLabels:
      app: phishing-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: phishing-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phishing-mysql-secret
                  key: mysql-root-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: phishing-mysql-storage
              mountPath: /var/lib/mysql
          command: ['sh', '-c', 'echo "CREATE DATABASE IF NOT EXISTS phishing_db; USE phishing_db; CREATE TABLE IF NOT EXISTS users (username VARCHAR(255) PRIMARY KEY, password VARCHAR(255), email VARCHAR(255)); CREATE TABLE IF NOT EXISTS reported_urls (id INT AUTO_INCREMENT PRIMARY KEY, url VARCHAR(255), prediction VARCHAR(50), probability FLOAT, reported_at DATETIME, username VARCHAR(255), FOREIGN KEY (username) REFERENCES users(username));" > /docker-entrypoint-initdb.d/init.sql && exec docker-entrypoint.sh mysqld']
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: phishing-mysql-storage
          persistentVolumeClaim:
            claimName: phishing-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: phishing-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: phishing-mysql
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: phishing-mysql-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phishing-mysql
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
